### ISSUE TITLE
Interview

### ISSUE THREAD

**Issue by tparnell8** [EhrgoHealth/CS6440#10]
Interview some people in the medial industry. Find out some of the following.

common weakness of current EHR's
Medication
7 pointed questions...about how our enhancement will beneficial if it is?.
Room for our enhancmenet (in the market)
Business case (high enough for money)

@codesoftly had some good suggestions that I forgot...if you remember them jot them down here....

**Comment by tparnell8** [comment]
Here is what I found out.

**Some** EHR systems do have a medication detector, in that they detect conflicting medications and alert. However most of these systems don't really work well, and are often baked right into the EHR. 

I found out that if we make a pluggable service that could replace the existing systems, and one that could check patient records against other providers, we could have a solid product. I found out that most systems do not alert prescribing doctors/nurses when a medications/treatments have a time component (ie, it needs to be taken in the morning/evening/etc), and that almost all of them do not alert when certain foods interfere with them (apparently quite a few medications cannot be taken with grape fruit for example).

I also found out that a lot of IV medications have to be administered in a certain way, and often IV medications cannot be combined (but at times can). If our system also handled cases for IV treatments it would go a long way to provide better care. 

The biggest thing I heard was that although some of these systems have this data, it is not exposed well or even at all. Accessing data about treatment schedules for medications (or general data/conflicts with other medications) via a phone would really improve care as doctors, and nurses could quickly check on something without having to go back to their computers. This wouldn't have to contain any patient data, just general information about various medications, and how they interact.

**Comment by codesoftly** [comment]
Excellent data, Tommy. I will have the project breakdown complete by
tomorrow night as the initial powerpoint.

**Comment by waryzh** [comment]
Nice job!

**Comment by dbcarey** [comment]
Excellent information. Nice work!
