### ISSUE TITLE
Create Architecture Diagram

### ISSUE THREAD

**Issue by Kakarot** [EhrgoHealth/CS6440#18]
Eric will create a UML architecture using Visual Studio. This is both for an agreed vision for implementation, and to satisfy **Team Deliverable 2**.

**Comment by codesoftly** [comment]
Based off updated expectation for architecture overview from the instructors, I just drew the architecture in PowerPoint. Furthermore, I've created and uploaded the initial PowerPoint slide for Team Deliverable 2.
