### ISSUE TITLE
What are the best times for you to chat via google hangouts?

### ISSUE THREAD

**Issue by tparnell8** [EhrgoHealth/CS6440#3]

**Comment by tparnell8** [comment]
Weekdays: 6am-7am, or 5pm - 10pm EST 
Weekends: Anytime

**Comment by waryzh** [comment]
weekdays: 7:30pm-10:30pm EST
weekends: most time

**Comment by dbcarey** [comment]
Weekdays Tuesday & Wednesday 7:30pm-10:00pm EST.
                  Monday, Thursday & Friday 6:30pm - 10:00 PM EST
Weekends - Saturdays after 11:00 a.m., Sunday anytime
These times are pretty flexible.  If we need to meet outside of those times I can usually make it work.

**Comment by tparnell8** [comment]
We have yet to hear from eric, but if it works for everyone I suggest we talk once a week on Saturday around 6:30 with hangouts (which I think for eric would be 4:30?)

Does that sound do-able for everyone?

**Comment by waryzh** [comment]
Works fine for me.

**Comment by dbcarey** [comment]
Works fine for me too.

**Comment by codesoftly** [comment]
I can meet 4:30/3:30 after daylight savings most Saturdays, there will be a few where we have family events (I will give you plenty of heads up). I am usually on toddler duty around then, so committing to more than an hour will be difficult.

**Comment by tparnell8** [comment]
yeah we should only chat for a half hour or so...nothing long just enough to get us on the same page :+1:

**Comment by tparnell8** [comment]
@dbcary @codesoftly what are your hangouts Email addresses?

**Comment by tparnell8** [comment]
@dbcarey

**Comment by tparnell8** [comment]
I just realized that @codesoftly has emailed us from a gmail account so we can hangouts with him already..

we just need @dbcarey's hangouts address
