### ISSUE TITLE
team name and add individual information in online spreadsheet

### ISSUE THREAD

**Issue by waryzh** [EhrgoHealth/CS6440#4]
We need a team name. 
Also please input your info in the spreadsheet, here is the link:
https://docs.google.com/spreadsheets/d/1Nk1P6atOC7rZRwmVFpJIFU50h36gwPQ8XYH19nlOWco/edit#gid=1715422678

**Comment by waryzh** [comment]
Looking at the spreadsheet, it seems most teams have 5-6 students, maybe we could recruit 1-2 more, what do you think?

**Comment by codesoftly** [comment]
A lot of people seem to be using HIT in their team names.  Carrying that torch, If we do an EHR focused project, we could name our team "Ehrgo Health" (take on the Latin word ergo, meaning "therefore"). If we want to get very geeky, we could use Ehrgo Proxy.

**Comment by tparnell8** [comment]
I think Ehrgo Health is a sick name

**Comment by tparnell8** [comment]
@waryzh @codesoftly @dbcarey  want to go with Ehrgo Health?

**Comment by dbcarey** [comment]
Sounds good to me.

**Comment by waryzh** [comment]
It's fine to me.

**Comment by codesoftly** [comment]
I added Ehrgo Health to the bottom of the spreadsheet. Please fill out your information. I am happy to take on whatever role is needed - but I would like to add another solid .ASP experienced front end programmer if possible.

**Comment by PeachDBC** [comment]
Information added.

**Comment by dbcarey** [comment]
Information added.  BTW - if you get any posts by PeachDBC that is also me.  I have a personal github account (and sometimes I forget to log out before using the one attached to GA Tech).  Sorry!!

**Comment by tparnell8** [comment]
:+1:
