### ISSUE TITLE
Team Formation Assignment #2

### ISSUE THREAD

**Issue by waryzh** [EhrgoHealth/CS6440#7]
Just a remainder. For this assignment, we need come up an idea for each of the four domains, not just the domain we chose.
I suggest each one of us do research on one different domain and come up with an idea for that domain.
such as 
Donna: Patient facing tools
Tommy: EHR enhancements
Eric: Population health
Harry: Clinical decision support

How is that?

**Comment by tparnell8** [comment]
That's fine.  We need this in by tomorrow so I'll try to come up with ideas for other ones as well in case other peoples missed this

**Comment by tparnell8** [comment]
EOD tomorrow that is

**Comment by codesoftly** [comment]
That's fine, I'll research my area. Are we still planning to meet at 6 PM
EDT today?

**Comment by tparnell8** [comment]
We can. If people will leave the email address registered to their acct here then we can get into a group chat. 

Tparnell8@gmail.com

I have Harry's

**Comment by waryzh** [comment]
y, let's meet today. Just to confirm the time for meeting will be 6:30pm EST (set up in another thread).

**Comment by tparnell8** [comment]
Great when is the team formation assignment due I was under the assumption that it was end of tomorrow but I could be wrong

**Comment by waryzh** [comment]
Based on T-Squre assignment, both Team Formation Assignment #1 and #2 are due at 5pm 2/2/2016.

**Comment by codesoftly** [comment]
The assignment is unclear how much we need to put into these ideas. I actually have a lot more study/ research/etc. behind this, but for now I'll just put up the blurb for Population health.

**Risk Tracker 
**
A system with two objectives: 1) to determine patient potential oncoming risks due to socioeconomic background, race, medical history, and current health indicators - notifying patient of optimal strategies for mitigation. 2) Use primary risk factors as use cases with ratio layouts to assist medical providers with identifying both acute and chronic conditions.

**Comment by waryzh** [comment]
Clinical Decision Support:
We will develop a web application to support clinical diagnosis and treatment decision for physicians/patents.  This tool will take input information from user and provide possible diagnoses. The information user may input includes symptoms, genetic data, health history, medications, test results, etc. For each possible diagnosis, the tool will also provide possible treatment suggestions. In summary, this tool will facilitate physicians/patients to make clinical diagnosis and treatment decision.

**Comment by waryzh** [comment]
Please take a look at the Assignment#2 in case there is any mistake..

[Team Formation Assignment#2 Ehrgo Health.pdf](https://github.com/EhrgoHealth/CS6440/files/113313/Team.Formation.Assignment.2.Ehrgo.Health.pdf)

**Comment by tparnell8** [comment]
:+1:

**Comment by waryzh** [comment]
submitted.
