### ISSUE TITLE
Our first meeting!!

### ISSUE THREAD

**Issue by tparnell8** [EhrgoHealth/CS6440#8]
As previously discussed we should meet today on hangouts I believe I have Harry's hang out and Eric's please make sure you give me your hangouts username so I can call you in the group chat. If You don't want to leave it here just email it to everyone

I will be calling everyone for a group chat at 6:30 as previously arranged.

**Comment by waryzh** [comment]
Sounds good, thanks.

**Comment by dbcarey** [comment]
I haven't used hangouts before, but I assume it is just my gmail username (?).  That is dbcarey

**Comment by tparnell8** [comment]
Yes you will need to install hangouts but yes its just like Skype but with your Google username

**Comment by waryzh** [comment]
I guess you also need sign in gmail/google account to receive call at that time.
