### ISSUE TITLE
EHR domain answer

### ISSUE THREAD

**Issue by tparnell8** [EhrgoHealth/CS6440#9]
for issue #7 (assignment 2)

EHR’s or Electronic Health records are systems that track a patient’s medical history. These systems include key administrative data relevant to a person’s care. These systems track various metrics such as weight, height, medications, vital signs, immunizations, lab data, etc. Most of the data in EHR’s can be used for additional analysis is not currently used. A plugin to EHR’s that tracks medications, and alerts when a medication is prescribed that can cause adverse reactions to medication that a patient is already on would save lives, and reduce mistakes during the prescription process. Such a feature could also know what allergies you have to certain medications, and makes sure that related medications are never prescribed to the patient. Also this system could suggest alternative medicines, or courses of treatment that may work better for this particular patient. 

Below is an attached word document that may be formatted a little better if you want it.

[EHRDomain.docx](https://github.com/EhrgoHealth/CS6440/files/111436/EHRDomain.docx)

**Comment by tparnell8** [comment]
@waryzh I posted my domain here

**Comment by dbcarey** [comment]
Did we want to include the AI feature in the project?  Here is what I have so far.

**Patient Facing Tools**
Patients are often overwhelmed by data given to them from practitioners.  Numbers and statistics are relatively meaningless unless they are communicated or interpreted into meaningful information.  This system would provide the patient their data in a very visual way that will allow them to monitor their health and make informed decisions.  The system could allow communication between the patient, their doctor and specialists that are involved in the patients care.  The patient would also be able to get more detailed information on medical terminology and prescribed medication directly from context links within the application itself.  The patient would also be able to schedule appointments with their doctor and receive appointment reminders. 

[Patient Facing Tools.docx](https://github.com/EhrgoHealth/CS6440/files/111597/Patient.Facing.Tools.docx)


@waryzh

**Comment by tparnell8** [comment]
its up to you we most certainly should either pick one or the other, and not both as its probably excessive in scope. That being said, this is certainly fine by me :+1:
